name: Post Tech Term to LinkedIn

on:
  schedule:
    # This is the alarm clock. It is set to run at 8:00 AM UTC every day.
    # You can change the '8' to any hour (0-23) you prefer.
    - cron: '0 8 * * *'
  # This line lets you run the robot manually from the Actions tab for testing.
  workflow_dispatch:

jobs:
  post-to-linkedin:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install necessary Python libraries
        run: pip install requests

      - name: Run the Python script to post
        env:
          # This gives our Python script access to the secret lockbox
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        run: python post_to_linkedin.py


